#!/bin/bash

SYSTEM=

if [[ $# -eq 0 || $# -gt 1 ]] ; then
    echo "Unable to run install script, please run with for example 'install desktop/laptop'"
    exit 1
else
	if [[ $1 = "laptop" ]]; then
		SYSTEM="laptop"
	else 
		SYSTEM="dekstop"
	fi	
fi

echo "Installing based on system: $SYSTEM"

echo -ne "
-------------------------------------------------------------------------
                    Main Packages
-------------------------------------------------------------------------
"

## GET SU PRIVILEGES
sudo -v
while true; do sudo -n true; sleep 300; kill -0 "$$" || exit; done 2>/dev/null &

# Configure DNF for Faster Downloads of Packages
echo -e "max_parallel_downloads=10\nfastestmirror=True" | sudo tee -a /etc/dnf/dnf.conf

# Fedora Update
sudo dnf update -y

# Enable RPM Fusion Repository
sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
sudo dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
echo "RPM Fusion Repository enabled"

pkgs='@base-x neofetch feh polybar rofi neovim vim bspwm sxhkd picom alacritty thunar zsh ranger nitrogen pavucontrol
xsensors unzip dunst cronie xclip xdg-utils xdotool firefox btop htop maim viewnior asciiquarium geany 
gvfs thunar-volman network-manager-applet iwd xdg-user-dirs bluez bluez-tools kitty toolbox flatpak 
acpi ufw thunar-archive-plugin xsetroot xautolock lxpolkit lxappearance xmodmap util-linux-user wget cowsay lolcat'

# Install Dependecies
sudo dnf install -y $pkgs # System Dependencies
sudo dnf install -y arc-theme papirus-icon-theme # System Themes
sudo dnf install -y make autoconf automake gcc gcc-c++ kernel-devel #Manual Compile And Install Dependencies
echo "Packages Installed"

# Add Flathub Repo
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

echo -ne "
-------------------------------------------------------------------------
                    3rd Packages
-------------------------------------------------------------------------
"

# Create necessary dir

cd ~
mkdir Downloads Pictures Documents Videos dev
mkdir ~/Pictures/screenshots ~/Pictures/wallpapers

if [ ! -d "~/.local/share/icons" ] 
then
    echo "Directory ~/.local/share/icons DOES NOT exists. Creating a new one" 
    sudo mkdir ~/.local/share/icons
fi
sudo chown $USER:$USER ~/.local/share/icons

if [ ! -d "~/.local/share/fonts" ] 
then
    echo "Directory /usr/share/fonts DOES NOT exists. Creating a new one" 
    mkdir ~/.local/share/fonts
fi
sudo chown $USER:$USER ~/.local/share/fonts

cd ~/repo

# Bibata Cursor
wget https://github.com/ful1e5/Bibata_Cursor/releases/download/v2.0.3/Bibata-Modern-Ice.tar.gz
tar -xvf Bibata-Modern-Ice.tar.gz
cp -r Bibata-Modern-Ice ~/.local/share/icons

# Pamixer
sudo dnf install -y meson pulseaudio-libs-devel cxxopts
git clone https://github.com/cdemoulins/pamixer.git
cd pamixer
meson setup build
sudo meson compile -C build
sudo meson install -C build
cd ..

#Tdrop
git clone https://github.com/noctuid/tdrop.git
cd tdrop
sudo make install
cd ..

# # Password Manager (1Password)
# sudo rpm --import https://downloads.1password.com/linux/keys/1password.asc
# sudo sh -c 'echo -e "[1password]\nname=1Password Stable Channel\nbaseurl=https://downloads.1password.com/linux/rpm/stable/\$basearch\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=\"https://downloads.1password.com/linux/keys/1password.asc\"" > /etc/yum.repos.d/1password.repo'
# sudo dnf install -y 1password

# Zscroll
git clone https://github.com/noctuid/zscroll
cd zscroll
sudo python3 setup.py install
cd ..

# Betterlockscreen
## Install dependencies
sudo dnf install -y autoconf automake cairo-devel fontconfig gcc libev-devel libjpeg-turbo-devel libXinerama libxkbcommon-devel libxkbcommon-x11-devel libXrandr pam-devel pkgconf xcb-util-image-devel xcb-util-xrm-devel ImageMagick
git clone https://github.com/Raymo111/i3lock-color.git
cd i3lock-color
./install-i3lock-color.sh
wget https://github.com/betterlockscreen/betterlockscreen/archive/refs/heads/main.zip
unzip main.zip
cd betterlockscreen-main/
chmod u+x betterlockscreen
sudo cp betterlockscreen ~/local/bin/
sudo cp system/betterlockscreen@.service /usr/lib/systemd/system/
sudo systemctl enable betterlockscreen@$USER
cd ..

if [[ $SYSTEM = "laptop" ]]; then
    # Brillo
    git clone https://github.com/CameronNemo/brillo.git
    cd brillo
    sudo make install.setgid
    echo "Brillo Installed"
    cd ..

    # Nbfc-linux    
    git clone https://github.com/nbfc-linux/nbfc-linux.git
    cd nbfc-linux
    sudo make install
    echo "Nbfc-linux Installed"
    cd ..

    # Auto-Cpufreq
    git clone https://github.com/AdnanHodzic/auto-cpufreq.git
    cd auto-cpufreq && sudo ./auto-cpufreq-installer
    sudo auto-cpufreq --install
    echo "Auto-Cpufreq Installed"
    cd ..

fi


echo -ne "
-------------------------------------------------------------------------
                     Set Config
-------------------------------------------------------------------------
"

cd ~/repo/bspwm/

#Copy Fonts
cp -r fonts/. ~/.local/share/fonts/
echo "Fonts Copied"

# Copy User's Config
cd ~/repo/bspwm
cp -r .config ~
cp .profile .xinitrc .Xresources .Xmodmap .gtkrc-2.0 ~/
sudo cp wallpaper/samurai.jpg /usr/share/backgrounds/
echo "Config folder copied"

#Copy User's Script
cp -r .local ~/

if [[ $SYSTEM = "desktop" ]]; then
    cd ~/.local/bin
    rm -rf changebrightness chargingnotify batterynotify
    cd ~/repo/bspwm
fi

echo "User's Script Copied"

#Set Btop Theme
btoptheme='color_theme = "/home/'$USER'/.config/btop/themes/tokyo-night.theme"'
sed -i "s@color_theme.*@$btoptheme@" ~/.config/btop/btop.conf
echo "Btop Theme Set"

# Copy Wallpaper
cp -r wallpaper/. /home/$USER/Pictures/wallpapers/
echo "Wallpaper Copied"

# #Remove default theme
# sudo rm /usr/share/icons/default/index.theme

# Laptop config
if [[ $SYSTEM = "laptop" ]]; then

    #Set Cronjob
	lines="*/5 * * * * /home/$USER/.local/bin/batterynotify"
    echo "$lines" | sudo crontab -u $USER

    # Set Udev Rules
    sudo cp bspwm/udev-rules/* /etc/udev/rules.d/
    echo "Udev rules Copied"
fi	


echo -ne "
-------------------------------------------------------------------------
                    Setup Firewall Rules
-------------------------------------------------------------------------
"

sudo ufw limit 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw allow 1443/tcp
sudo ufw allow 3306/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable

echo -ne "
-------------------------------------------------------------------------
                    Setup Zsh
-------------------------------------------------------------------------
"

# Get powerlevel10k theme for zsh
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/powerlevel10k

cd ~/.config/zsh/plugins
git clone https://github.com/MichaelAquilina/zsh-you-should-use.git
git clone https://github.com/zsh-users/zsh-autosuggestions.git
git clone https://github.com/zsh-users/zsh-history-substring-search.git
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
cd ~
sudo ln ~/.config/zsh/.zshrc .zshrc
sudo chsh -s /bin/zsh
sudo chsh -s /bin/zsh $USER

echo -ne "
-------------------------------------------------------------------------
                    Setup Login Manager
-------------------------------------------------------------------------
"

sudo dnf install -y lightdm lightdm-slick-greeter
sudo sed -i "s/#greeter-session=.*/greeter-session=slick-greeter/g" /etc/lightdm/lightdm.conf
echo "[Greeter]
background=/usr/share/backgrounds/samurai.jpg" | sudo tee /etc/lightdm/slick-greeter.conf
sudo systemctl enable lightdm
sudo systemctl set-default graphical.target
sudo rm /var/lib/AccountsService/users/$USER
sudo touch /var/lib/AccountsService/users/$USER
echo -e "[User]\nSession=\nXSession=bspwm" | sudo tee /var/lib/AccountsService/users/$USER
echo "LightDM enabled"


echo -ne "
-------------------------------------------------------------------------
                    Installation Complete, Please Reboot
-------------------------------------------------------------------------
"
sudo reboot now