#!/bin/bash

echo -ne "
-------------------------------------------------------------------------
                    Install Dependencies
-------------------------------------------------------------------------
"

## GET SU PRIVILEGES
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


pkgs='xorg xorg-xinit neofetch polybar rofi neovim vim bspwm sxhkd alacritty thunar zsh ranger nitrogen xsensors unzip dunst 
cronie xclip lightdm lightdm-slick-greeter xdg-utils xdo xdotool firefox btop htop maim lxsession lxappearance 
intellij-idea-community-edition viewnior ueberzug ttf-jetbrains-mono-nerd ttf-jetbrains-mono 
asciiquarium dbeaver geany papirus-icon-theme arc-gtk-theme pulseaudio pulseaudio-alsa pavucontrol pacman-contrib gvfs thunar-volman 
networkmanager network-manager-applet iwd xfce4-settings xdg-user-dirs bluez bluez-utils rofi-calc libreoffice-still kitty imagemagick acpi ufw'

for pkg in $pkgs; do
  if pacman -Qs $pkg > /dev/null ; then
    echo "$pkg installed"
  else
    echo "$pkg not installed"
  fi    
done

echo "Dependencies Checked"

sudo pacman -S --noconfirm lightdm-slick-greeter
echo "LightDM Slick Greeter Installed"
sudo sed -i "s/#greeter-session=.*/greeter-session=lightdm-slick-greeter/g" /etc/lightdm/lightdm.conf
MONITOR=xrandr | grep " connected " | awk '{ print$1 }'
sudo sed -i "s/#display-setup-script=.*/display-setup-script=xrandr --output $MONITOR --mode 3840x2160/g" /etc/lightdm/lightdm.conf
echo "[Greeter]
background=/usr/share/backgrounds/samurai.jpg" | sudo tee /etc/lightdm/slick-greeter.conf
echo "LightDM Setting Configured"

# Set Lockscreen
betterlockscreen -u /home/$USER/Pictures/wallpapers/samurai.jpg
echo "BetterLockscreen Set"

echo -ne "
-------------------------------------------------------------------------
                    Installation Complete
-------------------------------------------------------------------------
"