#!/bin/bash

echo -ne "
-------------------------------------------------------------------------
                    Install Dependencies
-------------------------------------------------------------------------
"

## GET SU PRIVILEGES
sudo -v
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


pkgs='xorg xorg-xinit neofetch polybar rofi neovim vim bspwm sxhkd alacritty thunar zsh ranger nitrogen xsensors unzip dunst 
cronie xclip lightdm lightdm-slick-greeter xdg-utils xdo xdotool firefox btop htop maim lxsession lxappearance 
intellij-idea-community-edition viewnior ueberzug ttf-jetbrains-mono-nerd ttf-jetbrains-mono 
asciiquarium dbeaver geany papirus-icon-theme arc-gtk-theme pulseaudio pulseaudio-alsa pavucontrol pacman-contrib gvfs thunar-volman 
networkmanager network-manager-applet iwd xfce4-settings xdg-user-dirs bluez bluez-utils rofi-calc libreoffice-still kitty imagemagick acpi ufw'

for pkg in $pkgs; do
  if pacman -Qs $pkg > /dev/null ; then
    echo "$pkg installed"
  else
    echo "$pkg not installed"
  fi    
done

echo "Dependencies Checked"

# Set Lockscreen
betterlockscreen -u ~/Pictures/wallpapers/samurai.jpg
echo "Lockscreen Set"

# Copy And Set Wallpaper
cp -r wallpaper/. ~/Pictures/wallpapers/
nitrogen --set-scaled ~/Pictures/wallpaper/samurai.jpg
echo "Wallpaper Set"

echo -ne "
-------------------------------------------------------------------------
                    Setup Login Manager
-------------------------------------------------------------------------
"
sudo pacman -S --noconfirm lightdm-slick-greeter 
echo "LightDM Slick Greeter Installed"
sudo cp -r ~/repo/bspwm/displaymanager/* /etc/
echo "LightDM Config Copied"

echo -ne "
-------------------------------------------------------------------------
                    Installation Complete
-------------------------------------------------------------------------
"



