#! /bin/sh

xrandr --auto &
xrandr --output Virtual1 --mode 1920x1080 &

bspc monitor -d 1 2 3 4 5 6 7 8 

## Apply bspwm configurations
bspc config border_width 3
bspc config window_gap 6.5
bspc config split_ratio 0.50

bspc config focused_border_color "#7BC5E4" 
bspc config normal_border_color "#32344A"
bspc config active_border_color "#444B6A"
bspc config presel_feedback_color "#61C766"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

#Thunar
bspc rule --add Thunar state=floating center=true

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off

# Autostart -----------------------------#

#Kill if already running
killall -9 sxhkd

sh $HOME/.config/polybar/polybar &
sxhkd -c ~/.config/sxhkd/sxhkdrc &
nitrogen --restore &
lxsession &
xsetroot -cursor_name left_ptr &
sh $HOME/.config/dunst/dunst
