#! /bin/sh

SCRIPT_DIR=~/.local/bin/

export _JAVA_AWT_WM_NONREPARENTING=1

#Display Setup
monitor

## Apply bspwm configurations
bspc config border_width 3
bspc config window_gap 20
bspc config split_ratio 0.50

bspc config focused_border_color "#7BC5E4" 
bspc config normal_border_color "#32344A"
bspc config active_border_color "#444B6A"
bspc config presel_feedback_color "#61C766"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

#Define screensize for floating window for multiple resolution
windowwidth=1000
windowheight=600
screenwidth=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $3}')
screenheight=$(xdpyinfo | awk -F'[ x]+' '/dimensions:/{print $4}')
windowx=$(("$screenwidth"/2-"$windowwidth"/2))
windowy=$(("$screenheight"/2-"$windowheight"/2))

#Intellij
bspc rule -a jetbrains-idea-ce follow=on desktop='^2'
#Postman
bspc rule -a Postman desktop='^3'
#DBeaver
bspc rule -a DBeaver desktop='^4'
#Citrix
bspc rule -a Wfica desktop='^5' state=pseudo_tiled follow=on
bspc rule -a "Windows sign-in" desktop='^5' state=floating
bspc rule -a "Wfica_Splash" desktop='^5' state=floating
bspc rule -a "Citrix Workspace" desktop='^5' state=pseudo_tiled
bspc rule -a "Remote Desktop Connection" desktop='^5' state=pseudo_tiled

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad Nitrogen \
Viewnior feh Nm-connection-editor 'Firefox:Places')
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on center=true rectangle="$windowwidth"x"$windowheight"+"$windowx"+"$windowy"; done

# Autostart -----------------------------#

#Kill if already running
killall -9 sxhkd
killall picom

sh $HOME/.config/polybar/polybar &
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Super_L|F1' &
ksuperkey -e 'Super_R=Super_L|F1' &

feh --bg-scale ~/Pictures/wallpapers/samurai.jpg
lxsession &
picom --legacy-backends &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
sh $HOME/.config/dunst/dunst
#pgrep bspswallow || bspswallow &
autolock &
#xfsettingsd &
pointer = 1 3 2