#! /bin/sh

export _JAVA_AWT_WM_NONREPARENTING=1

xrandr --auto &
xrandr --output Virtual1 --mode 3840x2160 &
#xrandr --output Virtual1 --mode 1920x1080 &

bspc monitor -d 1 2 3 4 5 6 7

workspaces() {
	name=1
	for monitor in `bspc query -M`; do
		bspc monitor ${monitor} -n "$name" -d '一' '二' '三' '四' '五' '六' '七'
		let name++
	done
}
workspaces

## Apply bspwm configurations
bspc config border_width 3
bspc config window_gap 6.5
bspc config split_ratio 0.50

bspc config focused_border_color "#7BC5E4" 
bspc config normal_border_color "#32344A"
bspc config active_border_color "#444B6A"
bspc config presel_feedback_color "#61C766"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

#Intellij
bspc rule -a jetbrains-idea-ce follow=on desktop='^2'
#Thunar
bspc rule --add Thunar state=floating center=true
#Postman
bspc rule -a Postman desktop='^3'
#DBeaver
bspc rule -a DBeaver desktop='^4'
#Citrix
bspc rule -a Wfica desktop='^7' state=pseudo_tiled follow=on
bspc rule -a "Windows sign-i7" desktop='^7' state=floating
bspc rule -a "Wfica_Splash" desktop='^7' state=floating
bspc rule -a "Citrix Workspace" desktop='^7' state=pseudo_tiled
bspc rule -a "Remote Desktop Connection" desktop='^7' state=pseudo_tiled

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Thunar Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

# Autostart -----------------------------#

#Kill if already running
killall -9 sxhkd
#killall picom

sh $HOME/.config/polybar/polybar &
sxhkd -c ~/.config/sxhkd/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Super_L|F1' &
ksuperkey -e 'Super_R=Super_L|F1' &


nitrogen --restore &
lxsession &
picom --legacy-backends &
xsetroot -cursor_name left_ptr &
sh $HOME/.config/dunst/dunst
pgrep bspswallow || bspswallow &
