#!/bin/bash

# rofi theme
theme="$HOME/.config/rofi/themes/screenshot.rasi"
IMG_PATH=/home/walter/Pictures/screenshot/
notify="notify-send -u low -t 2000 'Screenshot saved' -u normal"
output='/home/'$USER'/Pictures/screenshots/'$(date +%Y-%m-%d-%T)'-screenshot.png'

# options to be displayed
option0="  Screen"
option1="  Area"
option2="  Window"
option3="  Screen delay 5s"
option4="  Window delay 5s"

#option to save to
suboption0="  Clipboard"
suboption1="  File"

# options to be displyed
options="$option0\n$option1\n$option2\n$option3\n$option4"
suboptions="$suboption0\n$suboption1"

selected="$(echo -e "$options" | rofi -dmenu -i -selected-row 0 -theme "$theme")"
#subselected="$(echo -e "$suboptions" | rofi -dmenu -i -selected-row 0 -theme "$theme" -no-fixed-num-lines)"

case $selected in
    $option0)
		case "$(echo -e "$suboptions" | rofi -dmenu -i -selected-row 0 -theme "$theme" -no-fixed-num-lines)" in
			$suboption0)
				maim | xclip -selection clipboard -t image/png && $(eval "$notify");;
			$suboption1)
				sleep 0.2;
				maim "$output" | xclip -selection clipboard -t image/png && $(eval "$notify");;      
		esac;;
    $option1)
		case "$(echo -e "$suboptions" | rofi -dmenu -i -selected-row 0 -theme "$theme" -no-fixed-num-lines)" in
			$suboption0)
				maim -s | xclip -selection clipboard -t image/png && $(eval "$notify");;
			$suboption1)
				maim -s "$output" | xclip -selection clipboard -t image/png && $(eval "$notify");;
		esac;;
    $option2)
		case "$(echo -e "$suboptions" | rofi -dmenu -i -selected-row 0 -theme "$theme" -no-fixed-num-lines)" in
			$suboption0)
				maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png && $(eval "$notify");;
			$suboption1)
				maim -i $(xdotool getactivewindow) "$output" | xclip -selection clipboard -t image/png && $(eval "$notify");;
		esac;;
    $option3)
		case "$(echo -e "$suboptions" | rofi -dmenu -i -selected-row 0 -theme "$theme" -no-fixed-num-lines)" in
			$suboption0)
				sleep 5;
				maim | xclip -selection clipboard -t image/png && $(eval "$notify");;
			$suboption1)
				sleep 5;
				maim "$output" | xclip -selection clipboard -t image/png && $(eval "$notify");;
		esac;;
    $option4)
		case "$(echo -e "$suboptions" | rofi -dmenu -i -selected-row 0 -theme "$theme" -no-fixed-num-lines)" in
			$suboption0)
				sleep 5;
				maim -i | xclip -selection clipboard -t image/png && $(eval "$notify");;        
			$suboption1)
				sleep 5;
				maim -i $(xdotool getactivewindow) "$output" | xclip -selection clipboard -t image/png && $(eval "$notify");;        
		esac;;
	*)		
esac

