#!/bin/bash

DIR="$HOME/.config/polybar"
EXTERNAL_MONITOR="DisplayPort-0"

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar > /dev/null; do sleep 1; done

# Launch Polybar based on monitor input
for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
	MONITOR=$m polybar main --config="$DIR"/config.ini &
done

echo "Polybar launched..."
